baseurl = "/"
languageCode = "en-au"
title = "OJ's Perspective"
copyright = "Copyright OJ Reeves 2019"
theme = "ghostwriter"
themesdir = "themes"
paginatePath = "page"
paginate = 10
disqusShortname = "ojsrants"
googleAnalytics = ""

[Privacy]

[Privacy.disqus]
disable = true

[author]
name = "OJ Reeves"

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
post = "/posts/:slug/"

[params]
headling = "OJ's Perspective"
description = "Security and Software Development"
author = "OJ Reeves"
github = "https://github.com/OJ"
twitter = "https://twitter.com/TheColonial"
email = "oj@buffered.io"
opengraph = true
shareTwitter = true
dateFormat = "2006-01-02"
exponeaTrackVisits = false
readingTime = true
readingTimeText = "Read time:"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Live Streaming"
url = "/streaming/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 5

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 6
